[twitter]
alias = "tw"
default = "https://twitter.com"

[twitter.pages]
search = { prefix = "NONE", url = "https://twitter.com/search?q={encoded}" }
user = { prefix = "@", url = "https://twitter.com/{raw}" }




[github]
alias = "gh"
default = "https://github.com"

[github.pages]
search = { prefix = "-s", url = "https://github.com/search?q={encoded}"}
repo = { prefix = "NONE", url = "https://github.com/{raw}" }




[reddit]
alias = "rd"
default = "https://reddit.com"

[reddit.pages]
whatever = { prefix = "NONE", url = "https://reddit.com/{0}/{1}" }
search = { prefix = "-s", url = "https://reddit.com/search?q={encoded}" }
